export const genresOptions = [
  { id: 1, label: "Action and adventure", value: "action_and_adventure" },
  { id: 2, label: "Alternate history", value: " alternate_history" },
  { id: 3, label: "Anthology", value: " anthology" },
  { id: 4, label: "Chick lit", value: " chick_lit" },
  { id: 5, label: "Children's", value: " children" },
  { id: 6, label: "Classic", value: " classic" },
  { id: 7, label: "Comic book", value: "comic " },
  { id: 8, label: "Coming-of-age", value: "coming_of_age " },
  { id: 9, label: "Crime", value: "crime" },
  { id: 10, label: "Drama", value: "drama" },
  { id: 11, label: "Fairytale", value: "fairytale" },
  { id: 12, label: "Fantasy", value: "fantasy" },
  { id: 13, label: "Graphic novel", value: "graphic_novel" },
  { id: 14, label: "Historical fiction", value: "historical_fiction " },
  { id: 15, label: "Horror", value: "horror" },
  { id: 16, label: "Mystery", value: "mystery" },
  { id: 17, label: "Paranormal romance", value: "paranormal_romance" },
  { id: 18, label: "Poetry", value: "poetry" },
  { id: 19, label: "Political thriller", value: "political_thriller" },
  { id: 20, label: "Romance", value: "romance" },
  { id: 21, label: "Satire", value: "satire" },
  { id: 22, label: "Science fiction", value: "science_fiction" },
  { id: 23, label: "Art/architecture", value: "art" },
  { id: 24, label: "Biography", value: "biography" },
  { id: 25, label: "Business/economics", value: "business" },
  { id: 26, label: "Crafts/hobbies", value: "crafts" },
  { id: 27, label: "Cookbook", value: "cookbook" },
  { id: 28, label: "Diary", value: "diary" },
  { id: 29, label: "Dictionary", value: "dictionary" },
  { id: 30, label: "Encyclopedia", value: "encyclopedia" },
  { id: 31, label: "History", value: "history" },
  { id: 32, label: "Health/fitness", value: "health" },
  { id: 33, label: "Humor", value: "humor" },
  { id: 34, label: "Philosophy", value: "philosophy" },
  { id: 35, label: "Religion", value: "religion" },
  { id: 36, label: "Textbook", value: "textbook" },
  { id: 37, label: "True crime", value: "true_crime" },
  { id: 38, label: "Review", value: "review" },
  { id: 39, label: "Science", value: "science" },
  { id: 40, label: "Self help", value: "self_help" },
  { id: 41, label: "Sports and leisure", value: "sports_and_leisure" },
  { id: 42, genreTitle: "Travel", value: "travel" },
];
