export const bookGenres = [
  { id: 1, genreTitle: "Action and adventure", isSelected: false },
  { id: 2, genreTitle: "Alternate history", isSelected: false },
  { id: 3, genreTitle: "Anthology", isSelected: false },
  { id: 4, genreTitle: "Chick lit", isSelected: false },
  { id: 5, genreTitle: "Children's", isSelected: false },
  { id: 6, genreTitle: "Classic", isSelected: false },
  { id: 7, genreTitle: "Comic book", isSelected: false },
  { id: 8, genreTitle: "Coming-of-age", isSelected: false },
  { id: 9, genreTitle: "Crime", isSelected: false },
  { id: 10, genreTitle: "Drama", isSelected: false },
  { id: 11, genreTitle: "Fairytale", isSelected: false },
  { id: 12, genreTitle: "Fantasy", isSelected: false },
  { id: 13, genreTitle: "Graphic novel", isSelected: false },
  { id: 14, genreTitle: "Historical fiction", isSelected: false },
  { id: 15, genreTitle: "Horror", isSelected: false },
  { id: 16, genreTitle: "Mystery", isSelected: false },
  { id: 17, genreTitle: "Paranormal romance", isSelected: false },
  { id: 18, genreTitle: "Poetry", isSelected: false },
  { id: 19, genreTitle: "Political thriller", isSelected: false },
  { id: 20, genreTitle: "Romance", isSelected: false },
  { id: 21, genreTitle: "Satire", isSelected: false },
  { id: 22, genreTitle: "Science fiction", isSelected: false },
  { id: 23, genreTitle: "Art/architecture", isSelected: false },
  { id: 24, genreTitle: "Biography", isSelected: false },
  { id: 25, genreTitle: "Business/economics", isSelected: false },
  { id: 26, genreTitle: "Crafts/hobbies", isSelected: false },
  { id: 27, genreTitle: "Cookbook", isSelected: false },
  { id: 28, genreTitle: "Diary", isSelected: false },
  { id: 29, genreTitle: "Dictionary", isSelected: false },
  { id: 30, genreTitle: "Encyclopedia", isSelected: false },
  { id: 31, genreTitle: "History", isSelected: false },
  { id: 32, genreTitle: "Health/fitness", isSelected: false },
  { id: 33, genreTitle: "Humor", isSelected: false },
  { id: 34, genreTitle: "Philosophy", isSelected: false },
  {
    id: 35,
    genreTitle: "Religion, spirituality, and new age",
    isSelected: false,
  },
  { id: 36, genreTitle: "Textbook", isSelected: false },
  { id: 37, genreTitle: "True crime", isSelected: false },
  { id: 38, genreTitle: "Review", isSelected: false },
  { id: 39, genreTitle: "Science", isSelected: false },
  { id: 40, genreTitle: "Self help", isSelected: false },
  { id: 41, genreTitle: "Sports and leisure", isSelected: false },
  { id: 42, genreTitle: "Travel", isSelected: false },
];
